# Generated by Django 3.0.4 on 2020-04-02 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200402_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='PostDB',
        ),
    ]
