# Generated by Django 2.2.11 on 2020-04-08 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('maker', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('created_date', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
