# Generated by Django 2.2.11 on 2020-04-10 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUI', '0007_auto_20200408_2243'),
        ('ProductUI', '0002_auto_20200408_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Earphones', 'Earphones'), ('Charger', 'Charger'), ('Desktop', 'Desktop'), ('Smart Watchs', 'Smart Watches'), ('Speakers', 'Speakers'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('upvotes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LoginUI.Appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(blank=True, max_length=10)),
                ('processor', models.CharField(blank=True, max_length=20)),
                ('ram', models.CharField(blank=True, max_length=10)),
                ('storage', models.CharField(blank=True, max_length=10)),
                ('storage_type', models.CharField(blank=True, max_length=10)),
                ('battery', models.CharField(blank=True, max_length=10)),
                ('no_of_sims', models.CharField(blank=True, max_length=10)),
                ('wireless', models.CharField(blank=True, max_length=10)),
                ('cable_length', models.CharField(blank=True, max_length=10)),
                ('warrenty', models.CharField(blank=True, max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='ProductUI.Products')),
            ],
        ),
    ]
