# Generated by Django 2.2.11 on 2020-04-10 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductUI', '0003_auto_20200410_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ProductUI.Products'),
            preserve_default=False,
        ),
    ]
