# Generated by Django 2.2.11 on 2020-03-29 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.TextField(unique=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.state')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('pincode', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.city')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.state')),
            ],
        ),
        migrations.CreateModel(
            name='AppUserAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line1', models.CharField(max_length=50)),
                ('Address_line2', models.CharField(max_length=50)),
                ('area_name', models.CharField(max_length=20)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.city')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.area')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginUI.Appuser')),
            ],
        ),
    ]
