# Generated by Django 2.2.11 on 2020-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
