# Generated by Django 2.2.11 on 2020-03-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUI', '0002_auto_20200330_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='state_name',
        ),
    ]
