# Generated by Django 2.2.11 on 2020-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUI', '0003_remove_area_state_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuseraddresses',
            name='area_name',
        ),
        migrations.AddField(
            model_name='area',
            name='area_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
