# Generated by Django 3.0.3 on 2020-02-29 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(primary_key='true', serialize=False)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Mainpage.CustomerDetails')),
            ],
        ),
    ]
