# Generated by Django 3.0.3 on 2020-03-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0002_auto_20200301_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
