# Generated by Django 3.0.3 on 2020-03-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_auto_20200308_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
